# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Talks
    url: event/
    weight: 40
  - name: Publications
    url: publication/
    weight: 50
  - name: Projects
    url: '#projects'
    weight: 55
  - name: Library
    url: courses/
    weight: 60
  - name: Blog
    url: '#posts'
    weight: 65
  # - name: CV
  #   url: "uploads/resume.pdf"
  #   weight: 70
  - name: Contact
    url: '#contact'
    weight: 80
 
