---
title: "Impact Factor"
subtitle: ""
summary: and other metrics defined by Web of Science
authors: [admin]
slug: impact-factor
categories:
  - AcadeMD
tags:
  - WOS
  - Impact factor
date: 2022-04-11T10:17:50+03:00
lastmod: 2022-04-11T10:17:50+03:00
featured: false
draft: false
image:
  caption: ""
  focal_point: ""
  preview_only: false
projects: 
  - AcadeMD
links:
 - icon: github
   icon_pack: fab
   name: GitHub
   url: "https://github.com/AliGunerMD/aliguner/blob/main/content/post/2022-04-11-impact-factor/index.en.Rmd"
url_pdf: ""
url_code: ""
url_dataset: ""
url_project: ""
url_slides: ""
url_source: ""
url_video: ""
math: true
---


*Citation counts* are critical measures of the influence of an academic work. It is a part of [bibliometrics](https://en.wikipedia.org/wiki/Bibliometrics) which use statistical methods to analysis of scientific product.  

The Web of Science (WOS) database contains huge and great datasets analysing performance metrics of the journals.\
Its user interface has also improved with Clarivate™ and you can find a lot of useful information there.

Links for the website (registration required):\
[Web of Science Group - Master journal list](https://mjl.clarivate.com/home)\
[Clarivate - Journal citation reports](https://jcr.clarivate.com/jcr/home)\
[Clarivate - Browse journals](https://jcr.clarivate.com/jcr/browse-journals)

Here are some performance metrics used by Web of Science.  
<br>

# Impact Factor (IF) (or Journal Impact Factor = JIF):  

IF reflects the mean citation number in the last two years.

The [calculation](https://clarivate.com/webofsciencegroup/essays/impact-factor/#:~:text=The%20annual%20JCR%20impact%20factor,years%20(see%20Figure%201).) of Impact Factor (IF) is little bit tricky.  And It is published every year, usually in the following year. (2021-IFs will be published in June-2022)  

Here is the formula:  
<br>
$$
\begin{aligned}
     \textbf{IF 2021} = 
     \frac
     {
     \text{Citations in }\textbf{2021}
     \text{ to items published in }{\textbf{2019 & 2020}}
     }
     {
     \text{Citable items} 
     \text{ published in } {\textbf{2019 & 2020}}}
\end{aligned}
$$

# Journal Citation Indicator (JCI):  
JCI is the average category-normalized impact of citable items published over a recent three year period. 


## Other metrics for WOS:  
- 5-year Impact factor
- Eigenfactor Score    
- Normalized Eigenfactor  
- Article Influence Score  
- Immediacy Index  


# Some important notes for Academics:  

> **Impact Factor** is a metric specific to **Web of Science**. ([Scopus](https://www.scopus.com/sources) use "Cite score", [SCImago](https://www.scimagojr.com/journalrank.php) uses SJR as performance metrics.)

> **Citable items** (denominator of the formula) include only scholarly literature (articles, reviews, and case reports).  
NOT non-scholarly literature (editorials, comments, letter, etc.)   

> **Citations** (numerator of the formula) include all citations.  

> Onle **SCIE**-indexed and **SSCI**-indexed journals have Impact Factor. <u>AHCI- and ESCI-indexed journals do not have Impact Factor.</u>    

> ESCI-indexed journals have only JCI, but not Impact Factor.

> When the journals in each category are sorted from highest-to-lowest according to their performance metrics (JIF or JCI), and the list is divided into four groups, the top journal group is defined as first-quartile (**Q1 journals in the category**), the next is Q2, and the next ones Q3, Q4.

> **Journal IF** and **Journal CI** are different metrics. Therefore, there are 2 definition for quartiles. One is for IF, one for JCI. 

> Because all categories have various number of journals, and some journals belong to more than one category,  a journal can be classified in different quartiles (depends on the category).  
